language: node_js
node_js:
- stable
cache: npm
branches:
  only:
  - main
  - "/\\d+\\.\\d+\\.\\d+/"
script:
- npm test
- npm run lcov
- npm run build
deploy:
  provider: npm
  email: luna.bistuer@gmail.com
  api_key:
    secure: A7+o7A+IAG57un4mUdRU/CWI65YFjM8+7RIcfY4tV61tPf2MF4Lnj5LtSrHORV6he8pDm30nggjoiaX5INaE2l/yOek/DDUN3zRi70XnzHmTNmXFcDgcKy3PSrggX4DM9CcL4zoZ57GYM1kVP3xmvnyRcHCI37L8YFcGuUBfaeF/+436sOxqFFeIEoZFFhAwCf+L7NCPs5ejhDtRnTVddibs/f4BCCZc3F/PWes5mwtpEusv8H5QUvmz4f+r9mFjM1TLaiAoY0xmHHGOgitQrnUe9lOQfl6A5CS/IaRfGYnWdWaIx2GHbF4lXRuKoPoXReAG1dhHfaSLHb22kCabeCHA/220ZmMvU33xIHGeOFmcHzVmid3GMK5aAgh4qBkVwKe71ixPsGo/IG4iKmNpUT9c9yCa8IjxgKLtakDs6avlB0o9Ni/PDKGIECtdAFzP/gb/iV2u5kwIMY0h+hkniA/MjsbdW6pnC+hHaoSMCAznk/cY2sHnO+8F1iarUNrUgqkCtMxc8Q/atMOUorjQn1XhVvtW6cLwwV4y6N6GdackjBcbMe82LTz/bGD+9EbQaQoH4WHZ2U6+mPHOWh7esMZd1rwQAKnbOjhiyFhceJ0IkzyDNBfr1QYrdf+SVh/QrMiKeXLqSu3K9/ZsSHAgoZcnsZBPYb4W4U2eWAB9ipE=
  on:
    tags: true
    repo: david-luna/annotatron
    branch: main
  skip_cleanup: 'true'
